name: ShopkeepersAPISamples
version: '${pluginVersion}'
authors: [blablubbabc]
website: '${dboUrl}'
description: '${description}'

main: de.blablubbabc.shopkeepersAPIMMOItems.ShopkeepersAPIMMOItems
depend: [Shopkeepers, MMOItems, MythicLib]
